In [19]:
import pandas as pd

In [20]:
registration_df= pd.read_csv("../WidsPlotGraphs/Registration_data_Plotly.csv")
registration_df.head()

,Attendee Name,Status,Ticket_Name,Order_Id,Transaction Status,Registration Time,Gender,Designation,Organization,Outreach_Partner,Pincode/Zipcode/Postcode,"Total Experience in AI, ML, DS",Medium,Total Experience
0,Anuradha Jain,SUCCESS,Industry and General,7.010000e+17,SUCCESS,18-02-2021 20:07,Female,Founder Director,Bean Architect,Zensar,411057,0 > and < 1 year,WORD OF MOUTH,> 10 years
1,Ayushi Jain,SUCCESS,Students and Post Doctorates,5.300000e+17,SUCCESS,19-02-2021 20:01,Female,Student,Cummins College of Engineering for Women,TechGIG,482002,0 > and < 1 year,SOCIAL MEDIA WIDS PUNE,0 > and < 1 year
2,Devaki Kelkar,SUCCESS,"Academia, Faculty, Govt and Non Profits",1.560000e+17,SUCCESS,20-02-2021 16:30,Female,Senior Scientist,Prashanti Cancer Care Mission,TOMTOM,411016,3 years > and < 5 years,WORD OF MOUTH,> 10 years
3,Lenali,SUCCESS,"Academia, Faculty, Govt and Non Profits",4.510000e+17,SUCCESS,22-02-2021 10:21,Female,Associate Director,C-DAC,PubMatic,411008,3 years > and < 5 years,WORD OF MOUTH,> 10 years
4,Vibha Verma,SUCCESS,Industry and General,6.500000e+17,SUCCESS,22-02-2021 12:01,Female,Application Developer,Thoughtworks,RedHat,226021,1 year > and < 3 years,EMAIL,3 years > and < 5 years

In [21]:
registration_df['Registration Time'] = pd.to_datetime(registration_df['Registration Time'].astype(str),format='%d-%m-%Y %H:%S')
registration_df

,Attendee Name,Status,Ticket_Name,Order_Id,Transaction Status,Registration Time,Gender,Designation,Organization,Outreach_Partner,Pincode/Zipcode/Postcode,"Total Experience in AI, ML, DS",Medium,Total Experience
0,Anuradha Jain,SUCCESS,Industry and General,7.010000e+17,SUCCESS,2021-02-18 20:00:07,Female,Founder Director,Bean Architect,Zensar,411057,0 > and < 1 year,WORD OF MOUTH,> 10 years
1,Ayushi Jain,SUCCESS,Students and Post Doctorates,5.300000e+17,SUCCESS,2021-02-19 20:00:01,Female,Student,Cummins College of Engineering for Women,TechGIG,482002,0 > and < 1 year,SOCIAL MEDIA WIDS PUNE,0 > and < 1 year
2,Devaki Kelkar,SUCCESS,"Academia, Faculty, Govt and Non Profits",1.560000e+17,SUCCESS,2021-02-20 16:00:30,Female,Senior Scientist,Prashanti Cancer Care Mission,TOMTOM,411016,3 years > and < 5 years,WORD OF MOUTH,> 10 years
3,Lenali,SUCCESS,"Academia, Faculty, Govt and Non Profits",4.510000e+17,SUCCESS,2021-02-22 10:00:21,Female,Associate Director,C-DAC,PubMatic,411008,3 years > and < 5 years,WORD OF MOUTH,> 10 years
4,Vibha Verma,SUCCESS,Industry and General,6.500000e+17,SUCCESS,2021-02-22 12:00:01,Female,Application Developer,Thoughtworks,RedHat,226021,1 year > and < 3 years,EMAIL,3 years > and < 5 years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,Seema Puranik,SUCCESS,Industry and General,1.750000e+17,SUCCESS,2021-03-08 13:00:52,Female,Software Engineer,HCL,PubMatic,411057,0 > and < 1 year,SOCIAL MEDIA WIDS PUNE,3 years > and < 5 years
949,ANSHUMAN PANDEY,SUCCESS,Industry and General,3.040000e+17,SUCCESS,2021-03-08 14:00:48,Male,Tech Lead,SHL,Niramai,122001,3 years > and < 5 years,WORD OF MOUTH,3 years > and < 5 years
950,Ganesh,SUCCESS,Industry and General,4.760000e+17,SUCCESS,2021-03-08 15:00:39,Male,Cloud Consultant,Rapid Circle Pune,Niramai,411045,0 > and < 1 year,WORD OF MOUTH,3 years > and < 5 years
951,SushmaGoel,SUCCESS,Students and Post Doctorates,4.040000e+17,SUCCESS,2021-03-08 16:00:59,Female,Student,IT,Niramai,411014,0 > and < 1 year,OUT REACH PARTNER,3 years > and < 5 years
952,ANUPOJU NAVEEN,SUCCESS,Students and Post Doctorates,7.520000e+17,SUCCESS,2021-03-08 17:00:46,Male,Student,IIT Kharagpur,Niramai,535001,0 > and < 1 year,OUT REACH PARTNER,0 > and < 1 year

In [32]:
registration_df['Registration_date']=registration_df['Registration Time'].dt.date
registration_df

,Attendee Name,Status,Ticket_Name,Order_Id,Transaction Status,Registration Time,Gender,Designation,Organization,Outreach_Partner,Pincode/Zipcode/Postcode,"Total Experience in AI, ML, DS",Medium,Total Experience,Registration_date
0,Anuradha Jain,SUCCESS,Industry and General,7.010000e+17,SUCCESS,2021-02-18 20:00:07,Female,Founder Director,Bean Architect,Zensar,411057,0 > and < 1 year,WORD OF MOUTH,> 10 years,2021-02-18
1,Ayushi Jain,SUCCESS,Students and Post Doctorates,5.300000e+17,SUCCESS,2021-02-19 20:00:01,Female,Student,Cummins College of Engineering for Women,TechGIG,482002,0 > and < 1 year,SOCIAL MEDIA WIDS PUNE,0 > and < 1 year,2021-02-19
2,Devaki Kelkar,SUCCESS,"Academia, Faculty, Govt and Non Profits",1.560000e+17,SUCCESS,2021-02-20 16:00:30,Female,Senior Scientist,Prashanti Cancer Care Mission,TOMTOM,411016,3 years > and < 5 years,WORD OF MOUTH,> 10 years,2021-02-20
3,Lenali,SUCCESS,"Academia, Faculty, Govt and Non Profits",4.510000e+17,SUCCESS,2021-02-22 10:00:21,Female,Associate Director,C-DAC,PubMatic,411008,3 years > and < 5 years,WORD OF MOUTH,> 10 years,2021-02-22
4,Vibha Verma,SUCCESS,Industry and General,6.500000e+17,SUCCESS,2021-02-22 12:00:01,Female,Application Developer,Thoughtworks,RedHat,226021,1 year > and < 3 years,EMAIL,3 years > and < 5 years,2021-02-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,Seema Puranik,SUCCESS,Industry and General,1.750000e+17,SUCCESS,2021-03-08 13:00:52,Female,Software Engineer,HCL,PubMatic,411057,0 > and < 1 year,SOCIAL MEDIA WIDS PUNE,3 years > and < 5 years,2021-03-08
949,ANSHUMAN PANDEY,SUCCESS,Industry and General,3.040000e+17,SUCCESS,2021-03-08 14:00:48,Male,Tech Lead,SHL,Niramai,122001,3 years > and < 5 years,WORD OF MOUTH,3 years > and < 5 years,2021-03-08
950,Ganesh,SUCCESS,Industry and General,4.760000e+17,SUCCESS,2021-03-08 15:00:39,Male,Cloud Consultant,Rapid Circle Pune,Niramai,411045,0 > and < 1 year,WORD OF MOUTH,3 years > and < 5 years,2021-03-08
951,SushmaGoel,SUCCESS,Students and Post Doctorates,4.040000e+17,SUCCESS,2021-03-08 16:00:59,Female,Student,IT,Niramai,411014,0 > and < 1 year,OUT REACH PARTNER,3 years > and < 5 years,2021-03-08
952,ANUPOJU NAVEEN,SUCCESS,Students and Post Doctorates,7.520000e+17,SUCCESS,2021-03-08 17:00:46,Male,Student,IIT Kharagpur,Niramai,535001,0 > and < 1 year,OUT REACH PARTNER,0 > and < 1 year,2021-03-08

In [33]:
registration_df['Registration_date'].iloc[-1].strftime('%B %d, %Y')

'March 08, 2021'

In [34]:
registration_df_grp = pd.DataFrame(registration_df.groupby(['Registration_date','Outreach_Partner','Medium'])['Medium'].count().reset_index(name='Count'))
registration_df_grp

    Registration_date Outreach_Partner                  Medium  Count
0          2021-02-18           Zensar           WORD OF MOUTH      1
1          2021-02-19          TechGIG  SOCIAL MEDIA WIDS PUNE      1
2          2021-02-20           TOMTOM           WORD OF MOUTH      1
3          2021-02-22         PubMatic           WORD OF MOUTH      1
4          2021-02-22           RedHat                   EMAIL      1
..                ...              ...                     ...    ...
153        2021-03-08         PubMatic           WORD OF MOUTH      2
154        2021-03-08      Schumberger           WORD OF MOUTH      1
155        2021-03-08           Zensar                   EMAIL      1
156        2021-03-08           Zensar       OUT REACH PARTNER      1
157        2021-03-08           Zensar  SOCIAL MEDIA WIDS PUNE      1

[158 rows x 4 columns]

In [48]:
registration_medium = pd.DataFrame(registration_df_grp.drop(columns = 'Registration_date').groupby(['Outreach_Partner','Medium']).count().reset_index())
registration_medium

   Outreach_Partner                  Medium  Count
0         Accenture                   EMAIL      3
1         Accenture       OUT REACH PARTNER      3
2         Accenture  SOCIAL MEDIA WIDS PUNE      3
3         Accenture         WHATS APP GROUP      3
4         Accenture           WORD OF MOUTH      3
5           Niramai                   EMAIL      2
6           Niramai       OUT REACH PARTNER      2
7           Niramai  SOCIAL MEDIA WIDS PUNE      2
8           Niramai         WHATS APP GROUP      2
9           Niramai           WORD OF MOUTH      2
10       Persistant                   EMAIL      3
11       Persistant       OUT REACH PARTNER      3
12       Persistant  SOCIAL MEDIA WIDS PUNE      3
13       Persistant         WHATS APP GROUP      3
14       Persistant           WORD OF MOUTH      3
15         PubMatic                   EMAIL      3
16         PubMatic       OUT REACH PARTNER      2
17         PubMatic  SOCIAL MEDIA WIDS PUNE      3
18         PubMatic         WHATS APP GROUP      4
19         PubMatic           WORD OF MOUTH      7
20           RedHat                   EMAIL      4
21           RedHat       OUT REACH PARTNER      1
22           RedHat         WHATS APP GROUP      2
23           RedHat           WORD OF MOUTH      1
24      Schumberger                   EMAIL      5
25      Schumberger       OUT REACH PARTNER      6
26      Schumberger  SOCIAL MEDIA WIDS PUNE      5
27      Schumberger         WHATS APP GROUP      2
28      Schumberger           WORD OF MOUTH      4
29           TOMTOM                   EMAIL      4
30           TOMTOM       OUT REACH PARTNER      3
31           TOMTOM  SOCIAL MEDIA WIDS PUNE      2
32           TOMTOM         WHATS APP GROUP      1
33           TOMTOM           WORD OF MOUTH      2
34          TechGIG                   EMAIL      6
35          TechGIG       OUT REACH PARTNER      6
36          TechGIG  SOCIAL MEDIA WIDS PUNE      4
37          TechGIG         WHATS APP GROUP      2
38          TechGIG           WORD OF MOUTH      4
39           Zensar                   EMAIL      6
40           Zensar       OUT REACH PARTNER      7
41           Zensar  SOCIAL MEDIA WIDS PUNE      7
42           Zensar         WHATS APP GROUP      6
43           Zensar           WORD OF MOUTH      9

In [37]:
registration_outreachpartner = pd.DataFrame(registration_medium.pivot(index='Outreach_Partner', columns='Medium', values='Count')).reset_index().fillna(0)
registration_outreachpartner

Medium,Outreach_Partner,EMAIL,OUT REACH PARTNER,SOCIAL MEDIA WIDS PUNE,WHATS APP GROUP,WORD OF MOUTH
0,Accenture,3.0,3.0,3.0,3.0,3.0
1,Niramai,2.0,2.0,2.0,2.0,2.0
2,Persistant,3.0,3.0,3.0,3.0,3.0
3,PubMatic,3.0,2.0,3.0,4.0,7.0
4,RedHat,4.0,1.0,0.0,2.0,1.0
5,Schumberger,5.0,6.0,5.0,2.0,4.0
6,TOMTOM,4.0,3.0,2.0,1.0,2.0
7,TechGIG,6.0,6.0,4.0,2.0,4.0
8,Zensar,6.0,7.0,7.0,6.0,9.0

In [27]:
registration_medium = pd.DataFrame(registration_df_grp.groupby(['Medium'])['Count'].sum().reset_index(name='Total'))
registration_medium

                   Medium  Total
0                   EMAIL    279
1       OUT REACH PARTNER    127
2  SOCIAL MEDIA WIDS PUNE    102
3         WHATS APP GROUP    169
4           WORD OF MOUTH    276

In [59]:
registration_datewise = pd.DataFrame(registration_df_grp.groupby(['Registration_date','Outreach_Partner','Medium'])['Medium'].count().fillna(0).reset_index(name='Count'))
registration_datewise

    Registration_date Outreach_Partner                  Medium  Count
0          2021-02-18           Zensar           WORD OF MOUTH      1
1          2021-02-19          TechGIG  SOCIAL MEDIA WIDS PUNE      1
2          2021-02-20           TOMTOM           WORD OF MOUTH      1
3          2021-02-22         PubMatic           WORD OF MOUTH      1
4          2021-02-22           RedHat                   EMAIL      1
..                ...              ...                     ...    ...
153        2021-03-08         PubMatic           WORD OF MOUTH      1
154        2021-03-08      Schumberger           WORD OF MOUTH      1
155        2021-03-08           Zensar                   EMAIL      1
156        2021-03-08           Zensar       OUT REACH PARTNER      1
157        2021-03-08           Zensar  SOCIAL MEDIA WIDS PUNE      1

[158 rows x 4 columns]

In [64]:
registration_partner = registration_datewise[registration_datewise['Outreach_Partner']=='Accenture'].groupby(['Registration_date'])['Count'].sum().reset_index()
registration_partner

  Registration_date  Count
0        2021-03-03      5
1        2021-03-04      5
2        2021-03-05      5